version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/vut-db
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=vut-db
